### ISSUE TITLE
RU1: All options should work (not only Change Propagation)

### ISSUE THREAD

**Issue by javierobledo** [JSwingRipples2016/jswingripples#19]
**Description:**
 There's six different types of analysis in the jswingripples application. The "Change Propagation (Relaxed)" is the only one working. All options should work like they do in the original jripples plugin for eclipse.

Priority: High
Users: Developers
Source: Team / Teacher

Usage: 
Here's a example of usage of RU1

**Software Requeriments**
- [ ] Iteration 1
- [ ] RS1: "Concept Location (Relaxed)" analysis should work #30
- [ ] RS2: "Concept Location" analysis should work #31
- [ ] RS3: "Impact Analysis" should work #32 
- [ ] RS4: "Impact Analysis (Relaxed)" should work #33 
- [ ] RS5: "Change Propagation" analysis should work #34
